version: "3.1"

services:

  startrip_db:
    image: mongo
    container_name: startrip_db_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/ariel/Desenvolvimento/Docker/Volumes/MongoDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: startripdba
      MONGO_INITDB_ROOT_PASSWORD: StarTripAdmin2023

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_RETRY_TOPIC_ENABLED: false

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=StarTrip
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka

#  st_usuarios:
#    image: 'st-usuarios:1.0'
#    build:
#      dockerfile: st-usuarios/Dockerfile
#      context: .
#    container_name: st-usuarios
#    ports:
#      - '7001:7001'
#    depends_on:
#      - startrip_db
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://startripdba:StarTripAdmin2023@startrip_db:27017/StUsuarios?authSource=admin&authMechanism=SCRAM-SHA-256
#
#  st_imoveis:
#    image: 'st-imoveis:1.0'
#    build:
#      dockerfile: st-imoveis/Dockerfile
#      context: .
#    container_name: st-imoveis
#    ports:
#      - '7002:7002'
#    depends_on:
#      - startrip_db
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://startripdba:StarTripAdmin2023@startrip_db:27017/StImoveis?authSource=admin&authMechanism=SCRAM-SHA-256
#
#  st_anuncios:
#    image: 'st-anuncios:1.0'
#    build:
#      dockerfile: st-anuncios/Dockerfile
#      context: .
#    container_name: st-anuncios
#    ports:
#      - '7003:7003'
#    depends_on:
#      - startrip_db
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://startripdba:StarTripAdmin2023@startrip_db:27017/StAnuncios?authSource=admin&authMechanism=SCRAM-SHA-256
#
#  st_reservas:
#    image: 'st-reservas:1.0'
#    build:
#      dockerfile: st-reservas/Dockerfile
#      context: .
#    container_name: st-reservas
#    ports:
#      - '7004:7004'
#    depends_on:
#      - startrip_db
#      - kafka
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://startripdba:StarTripAdmin2023@startrip_db:27017/StReservas?authSource=admin&authMechanism=SCRAM-SHA-256
#
#  st_pagamentos:
#    image: 'st-pagamentos:1.0'
#    build:
#      dockerfile: st-pagamentos/Dockerfile
#      context: .
#    container_name: st-pagamentos
#    ports:
#      - '7005:7005'
#    depends_on:
#      - startrip_db
#      - kafka
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://startripdba:StarTripAdmin2023@startrip_db:27017/StPagamentos?authSource=admin&authMechanism=SCRAM-SHA-256
