server:
  port: 7004

spring:
  data:
    mongodb:
      uri: mongodb://startripdba:StarTripAdmin2023@localhost:27017/StReservas?authSource=admin&authMechanism=SCRAM-SHA-256

reservas:
  urls:
    api-st-usuarios: localhost:7001/usuarios
    api-st-imoveis: localhost:7002/imoveis
    api-st-anuncios: localhost:7003/anuncios
